version: '3.9'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    expose:
      - 8000  # Expose Gunicorn port

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"  # Map host port 80 to container port 80
    depends_on:
      - django
    volumes:
      - ./static:/app/static  # Mount static files for Nginx
